### ISSUE TITLE
Gestión de proyectos

### ISSUE THREAD

**Issue by pfd1004** [dmh1006/PR2-Scrum-Master#12]
![image](https://user-images.githubusercontent.com/127233554/232047497-61cace85-e6e8-4db9-94fc-f1457fe115fe.png)

1. **Desarrollo**
El desarrollo del proyecto puede darse de forma completa o incremental.

2. **Trabajo**
La forma de trabajar puede ser secuencial («en cascada») o concurrente

3. **Conocimiento**
Los diferentes modelos pueden ubicar el conocimiento o bien en los procesos o en
las personas.

**Comment by pfd1004** [comment]
Os gusta como queda la foto?

**Comment by dmh1006** [comment]
queda perfecta, asi genial

**Comment by rdl1004** [comment]
Muy visual, me gusta!
