### ISSUE TITLE
El Manifiesto Agil

### ISSUE THREAD

**Issue by dmh1006** [dmh1006/PR2-Scrum-Master#2]
Con este trabajo hemos llegado a valorar: • A los individuos y su interacción, por encima de los procesos y las herramientas.
En la reunión se acuñó el término «métodos ágiles» para definir a aquellos que estaban surgiendo como alternativa a las metodologías formales, tales como CMMSW (precursor de CMMI), PMI, SPICE (proyecto inicial de ISO 15504, a su vez precursor de ISO 33000)… a los que consideraban excesivamente pesados y rígidos por su carácter normativo y fuerte dependencia de planificaciones detalladas previas al desarrollo.
16 «Valoramos más a los individuos y su interacción que a los procesos y las herramientas.
En una producción basada en procesos, lo que se persigue es que la calidad del resultado sea consecuencia de éstos, más que del conocimiento aportado por las personas que los ejecutan.
En el desarrollo ágil, en cambio, los procesos son sólo una ayuda; un soporte para guiar el trabajo.
17 «Valoramos más el software que funciona, por encima de la documentación exhaustiva.
Se puede argumentar que la documentación detallada facilita transmitir información entre las personas implicadas en el proyecto, pero rara vez es así.
» El objetivo de un proyecto ágil no es controlar la ejecución para garantizar que los planes iniciales se cumplen, sino proporcionar de forma continua el mayor valor posible al producto.
Es más eficiente tomar feedback directo a la vez que se desarrolla el producto, y en consecuencia redefinir y mejorar los requisitos de las partes que quedan.
Para que el cliente sea consciente de los cambios conforme van surgiendo, debe acompañar al equipo durante el proceso.
La mejor relación entre cliente y equipo es una de implicación y colaboración directa, no una contractual, que tiende a delimitar responsabilidades al principio del proyecto y ya está.
» Los principales valores de la gestión ágil son la anticipación y la adaptación, diferentes a los de la gestión de proyectos ortodoxa: planificación y control para garantizar el cumplimiento del plan.
Para desarrollar productos de requisitos inestables, en los que es inherente el cambio y la evolución rápida y continua, resulta mucho más valiosa la capacidad de respuesta que la de seguimiento y aseguramiento de planes.
Los procesos ágiles se doblegan al cambio como ventaja competitiva para el cliente.

**Comment by dmh1006** [comment]
He intentado hacer lo bien pero igual echale un ojo Pablo

**Comment by pfd1004** [comment]
Yo lo veo bien, buen trabajo!
